version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Installing dependencies"
      - go mod tidy

  build:
    commands:
      - echo "Running tests"
      - go test -v -timeout 30m ./...

artifacts:
  files:
    - '**/*'
